-- MySQL Script generated by MySQL Workbench
-- Mon Apr  1 19:55:22 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user_info` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user_info` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` CHAR(10) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `role` VARCHAR(32) NOT NULL,
  `realname` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC));


-- -----------------------------------------------------
-- Table `mydb`.`student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`student` ;

CREATE TABLE IF NOT EXISTS `mydb`.`student` (
  `user_id` INT UNSIGNED NOT NULL,
  `nickname` VARCHAR(128) NULL,
  `grade` VARCHAR(16) NULL,
  `college` VARCHAR(128) NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_student_userinfo`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`teacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`teacher` ;

CREATE TABLE IF NOT EXISTS `mydb`.`teacher` (
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_teacher_userinfo`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`course` ;

CREATE TABLE IF NOT EXISTS `mydb`.`course` (
  `course_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `teacher_id` INT UNSIGNED NOT NULL,
  `course_name` VARCHAR(128) NOT NULL,
  `description` TEXT NOT NULL,
  `period` TINYINT NOT NULL,
  `start_time` DATE NOT NULL,
  `finish_time` DATE NOT NULL,
  PRIMARY KEY (`course_id`),
  INDEX `fk_course_teacher_idx` (`teacher_id` ASC),
  CONSTRAINT `fk_course_teacher`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `mydb`.`teacher` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`experiment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`experiment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`experiment` (
  `experiment_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `experiment_name` VARCHAR(256) NOT NULL,
  `description` TEXT NULL,
  `start_time` DATE NOT NULL,
  `finish_time` DATE NOT NULL,
  `course_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`experiment_id`),
  INDEX `fk_experiment_course_idx` (`course_id` ASC),
  CONSTRAINT `fk_experiment_course`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`application`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`application` ;

CREATE TABLE IF NOT EXISTS `mydb`.`application` (
  `student_user_id` INT UNSIGNED NOT NULL,
  `course_course_id` INT UNSIGNED NOT NULL,
  `apply_time` DATETIME NOT NULL,
  `state` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`student_user_id`, `course_course_id`),
  INDEX `fk_student_has_course_course1_idx` (`course_course_id` ASC),
  INDEX `fk_student_has_course_student1_idx` (`student_user_id` ASC),
  CONSTRAINT `fk_student_has_course_student1`
    FOREIGN KEY (`student_user_id`)
    REFERENCES `mydb`.`student` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_has_course_course1`
    FOREIGN KEY (`course_course_id`)
    REFERENCES `mydb`.`course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`selected_course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`selected_course` ;

CREATE TABLE IF NOT EXISTS `mydb`.`selected_course` (
  `student_user_id` INT UNSIGNED NOT NULL,
  `course_course_id` INT UNSIGNED NOT NULL,
  `approve_time` DATETIME NOT NULL,
  `avg_online_score` DECIMAL(5,1) NULL,
  `mid_score` DECIMAL(5,1) NULL,
  `final_score` DECIMAL(5,1) NULL,
  `total_score` DECIMAL(5,1) NULL,
  PRIMARY KEY (`student_user_id`, `course_course_id`),
  INDEX `fk_student_has_course_course2_idx` (`course_course_id` ASC),
  INDEX `fk_student_has_course_student2_idx` (`student_user_id` ASC),
  CONSTRAINT `fk_student_has_course_student2`
    FOREIGN KEY (`student_user_id`)
    REFERENCES `mydb`.`student` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_has_course_course2`
    FOREIGN KEY (`course_course_id`)
    REFERENCES `mydb`.`course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`chapter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`chapter` ;

CREATE TABLE IF NOT EXISTS `mydb`.`chapter` (
  `chapter_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `course_id` INT UNSIGNED NOT NULL,
  `sequence` TINYINT UNSIGNED NOT NULL,
  `chapter_name` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`chapter_id`),
  INDEX `fk_chapter_couser_idx` (`course_id` ASC),
  CONSTRAINT `fk_chapter_couser`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`filesource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`filesource` ;

CREATE TABLE IF NOT EXISTS `mydb`.`filesource` (
  `filesouce_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `filename` VARCHAR(256) NOT NULL,
  `identifier` VARCHAR(256) NOT NULL,
  `filetype` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`filesouce_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`section`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`section` ;

CREATE TABLE IF NOT EXISTS `mydb`.`section` (
  `section_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `chapter_id` INT UNSIGNED NOT NULL,
  `sequence` TINYINT NOT NULL,
  `section_name` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`section_id`),
  INDEX `fk_section_chapter_idx` (`chapter_id` ASC),
  CONSTRAINT `fk_section_chapter`
    FOREIGN KEY (`chapter_id`)
    REFERENCES `mydb`.`chapter` (`chapter_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student_course_approve_has_experiment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`student_course_approve_has_experiment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`student_course_approve_has_experiment` (
  `student_course_approve_student_user_id` INT UNSIGNED NOT NULL,
  `student_course_approve_course_course_id` INT UNSIGNED NOT NULL,
  `experiment_experiment_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`student_course_approve_student_user_id`, `student_course_approve_course_course_id`, `experiment_experiment_id`),
  INDEX `fk_student_course_approve_has_experiment_experiment1_idx` (`experiment_experiment_id` ASC),
  INDEX `fk_student_course_approve_has_experiment_student_course_app_idx` (`student_course_approve_student_user_id` ASC, `student_course_approve_course_course_id` ASC),
  CONSTRAINT `fk_student_course_approve_has_experiment_student_course_appro1`
    FOREIGN KEY (`student_course_approve_student_user_id` , `student_course_approve_course_course_id`)
    REFERENCES `mydb`.`selected_course` (`student_user_id` , `course_course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_course_approve_has_experiment_experiment1`
    FOREIGN KEY (`experiment_experiment_id`)
    REFERENCES `mydb`.`experiment` (`experiment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`experiment_file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`experiment_file` ;

CREATE TABLE IF NOT EXISTS `mydb`.`experiment_file` (
  `experiment_experiment_id` INT UNSIGNED NOT NULL,
  `filesource_filesouce_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`experiment_experiment_id`, `filesource_filesouce_id`),
  INDEX `fk_experiment_has_filesource_filesource1_idx` (`filesource_filesouce_id` ASC),
  INDEX `fk_experiment_has_filesource_experiment1_idx` (`experiment_experiment_id` ASC),
  CONSTRAINT `fk_experiment_has_filesource_experiment1`
    FOREIGN KEY (`experiment_experiment_id`)
    REFERENCES `mydb`.`experiment` (`experiment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_experiment_has_filesource_filesource1`
    FOREIGN KEY (`filesource_filesouce_id`)
    REFERENCES `mydb`.`filesource` (`filesouce_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student_course_approve_has_experiment_has_filesource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`student_course_approve_has_experiment_has_filesource` ;

CREATE TABLE IF NOT EXISTS `mydb`.`student_course_approve_has_experiment_has_filesource` (
  `student_user_id` INT UNSIGNED NOT NULL,
  `course_id` INT UNSIGNED NOT NULL,
  `experiment_id` INT UNSIGNED NOT NULL,
  `file` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`student_user_id`, `course_id`, `experiment_id`),
  INDEX `fk_student_course_approve_has_experiment_has_filesource_fil_idx` (`file` ASC),
  INDEX `fk_student_course_approve_has_experiment_has_filesource_stu_idx` (`student_user_id` ASC, `course_id` ASC, `experiment_id` ASC),
  CONSTRAINT `fk_student_course_approve_has_experiment_has_filesource_stude1`
    FOREIGN KEY (`student_user_id` , `course_id` , `experiment_id`)
    REFERENCES `mydb`.`student_course_approve_has_experiment` (`student_course_approve_student_user_id` , `student_course_approve_course_course_id` , `experiment_experiment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_course_approve_has_experiment_has_filesource_files1`
    FOREIGN KEY (`file`)
    REFERENCES `mydb`.`filesource` (`filesouce_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`chapter_file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`chapter_file` ;

CREATE TABLE IF NOT EXISTS `mydb`.`chapter_file` (
  `chapter_chapter_id` INT UNSIGNED NOT NULL,
  `filesource_filesouce_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`chapter_chapter_id`, `filesource_filesouce_id`),
  INDEX `fk_chapter_has_filesource_filesource1_idx` (`filesource_filesouce_id` ASC),
  INDEX `fk_chapter_has_filesource_chapter1_idx` (`chapter_chapter_id` ASC),
  CONSTRAINT `fk_chapter_has_filesource_chapter1`
    FOREIGN KEY (`chapter_chapter_id`)
    REFERENCES `mydb`.`chapter` (`chapter_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chapter_has_filesource_filesource1`
    FOREIGN KEY (`filesource_filesouce_id`)
    REFERENCES `mydb`.`filesource` (`filesouce_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`section_file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`section_file` ;

CREATE TABLE IF NOT EXISTS `mydb`.`section_file` (
  `section_section_id` INT UNSIGNED NOT NULL,
  `filesource_filesouce_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`section_section_id`, `filesource_filesouce_id`),
  INDEX `fk_section_has_filesource_filesource1_idx` (`filesource_filesouce_id` ASC),
  INDEX `fk_section_has_filesource_section1_idx` (`section_section_id` ASC),
  CONSTRAINT `fk_section_has_filesource_section1`
    FOREIGN KEY (`section_section_id`)
    REFERENCES `mydb`.`section` (`section_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_section_has_filesource_filesource1`
    FOREIGN KEY (`filesource_filesouce_id`)
    REFERENCES `mydb`.`filesource` (`filesouce_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student_course_experiment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`student_course_experiment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`student_course_experiment` (
  `student_id` INT UNSIGNED NOT NULL,
  `course_id` INT UNSIGNED NOT NULL,
  `experiment_experiment_id` INT UNSIGNED NOT NULL,
  `doc_file` INT UNSIGNED NOT NULL,
  `vedio_file` INT UNSIGNED NOT NULL,
  `score` INT UNSIGNED NULL,
  PRIMARY KEY (`student_id`, `course_id`, `experiment_experiment_id`),
  INDEX `fk_student_course_approve_has_experiment1_experiment1_idx` (`experiment_experiment_id` ASC),
  INDEX `fk_student_course_approve_has_experiment1_student_course_ap_idx` (`student_id` ASC, `course_id` ASC),
  INDEX `fk_stu_course_exp_file_idx` (`doc_file` ASC),
  INDEX `fk_stu_course_exp_file2_idx` (`vedio_file` ASC),
  CONSTRAINT `fk_student_course_approve_has_experiment1_student_course_appr1`
    FOREIGN KEY (`student_id` , `course_id`)
    REFERENCES `mydb`.`selected_course` (`student_user_id` , `course_course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_course_approve_has_experiment1_experiment1`
    FOREIGN KEY (`experiment_experiment_id`)
    REFERENCES `mydb`.`experiment` (`experiment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stu_course_exp_file`
    FOREIGN KEY (`doc_file`)
    REFERENCES `mydb`.`filesource` (`filesouce_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stu_course_exp_file2`
    FOREIGN KEY (`vedio_file`)
    REFERENCES `mydb`.`filesource` (`filesouce_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`exam`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`exam` ;

CREATE TABLE IF NOT EXISTS `mydb`.`exam` (
  `exam_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `chapter_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`exam_id`),
  INDEX `fk_exam_chapter_idx` (`chapter_id` ASC),
  CONSTRAINT `fk_exam_chapter`
    FOREIGN KEY (`chapter_id`)
    REFERENCES `mydb`.`chapter` (`chapter_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`option`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`option` ;

CREATE TABLE IF NOT EXISTS `mydb`.`option` (
  `option_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `option_detail` VARCHAR(256) NOT NULL,
  `question_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`option_id`),
  INDEX `fk_question_option_idx` (`question_id` ASC),
  CONSTRAINT `fk_question_option`
    FOREIGN KEY (`question_id`)
    REFERENCES `mydb`.`question` (`question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`question` ;

CREATE TABLE IF NOT EXISTS `mydb`.`question` (
  `question_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `exam` INT UNSIGNED NOT NULL,
  `answer` INT UNSIGNED NOT NULL,
  `detail` TEXT NOT NULL,
  PRIMARY KEY (`question_id`),
  INDEX `fk_exam_question_idx` (`exam` ASC),
  INDEX `fk_question_answer_idx` (`answer` ASC),
  UNIQUE INDEX `answer_UNIQUE` (`answer` ASC),
  CONSTRAINT `fk_exam_question`
    FOREIGN KEY (`exam`)
    REFERENCES `mydb`.`exam` (`exam_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_question_answer`
    FOREIGN KEY (`answer`)
    REFERENCES `mydb`.`option` (`option_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`notice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`notice` ;

CREATE TABLE IF NOT EXISTS `mydb`.`notice` (
  `notice_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `author` INT UNSIGNED NOT NULL,
  `title` VARCHAR(128) NOT NULL,
  `detail` TEXT NOT NULL,
  `date_create` DATETIME NOT NULL,
  PRIMARY KEY (`notice_id`),
  INDEX `fk_notiece_author_idx` (`author` ASC),
  CONSTRAINT `fk_notiece_author`
    FOREIGN KEY (`author`)
    REFERENCES `mydb`.`teacher` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`message` ;

CREATE TABLE IF NOT EXISTS `mydb`.`message` (
  `message_id` INT UNSIGNED NOT NULL,
  `author` INT UNSIGNED NOT NULL,
  `content` TEXT NOT NULL,
  `create_time` DATETIME NOT NULL,
  `reply_to` INT UNSIGNED NULL,
  PRIMARY KEY (`message_id`),
  INDEX `fk_message_reply_idx` (`reply_to` ASC),
  INDEX `fk_message_author_idx` (`author` ASC),
  CONSTRAINT `fk_message_reply`
    FOREIGN KEY (`reply_to`)
    REFERENCES `mydb`.`message` (`message_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_author`
    FOREIGN KEY (`author`)
    REFERENCES `mydb`.`user_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
